name: Build and Upload Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IMAGE_TAG: "newapiselfbuild:v0.4.6.1"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: |
        docker build -t $IMAGE_TAG .

    - name: Save Docker image to a tar file
      run: |
        docker save $IMAGE_TAG | gzip > newapiselfbuild.tar.gz
        echo "File size of newapiselfbuild.tar.gz:"
        ls -lh newapiselfbuild.tar.gz

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image to Docker Hub
      run: |
        docker tag $IMAGE_TAG ${{ secrets.DOCKER_USERNAME }}/newapiselfbuild
        docker push ${{ secrets.DOCKER_USERNAME }}/newapiselfbuild